<a href="https://colab.research.google.com/github/Shakya-Chakraborty/ML-Projects/blob/main/Credit_Card_Approval/Credit_Card_Approval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Library


In [ ]:
import pandas as pd
import numpy as np

#Importing Dataset


In [ ]:
dataset = pd.read_csv("cc_approvals.data", header = None)

In [ ]:
print(dataset)

    0      1       2  3  4   5   6     7  8  9   10 11 12     13   14 15
0    b  30.83   0.000  u  g   w   v  1.25  t  t   1  f  g  00202    0  +
1    a  58.67   4.460  u  g   q   h  3.04  t  t   6  f  g  00043  560  +
2    a  24.50   0.500  u  g   q   h  1.50  t  f   0  f  g  00280  824  +
3    b  27.83   1.540  u  g   w   v  3.75  t  t   5  t  g  00100    3  +
4    b  20.17   5.625  u  g   w   v  1.71  t  f   0  f  s  00120    0  +
..  ..    ...     ... .. ..  ..  ..   ... .. ..  .. .. ..    ...  ... ..
685  b  21.08  10.085  y  p   e   h  1.25  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.00  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.00  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.04  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.29  f  f   0  t  g  00000    0  -

[690 rows x 16 columns]


#Inspecting the dataset

In [ ]:
dataset.describe()

2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       690 non-null    object 
 1   1       690 non-null    object 
 2   2       690 non-null    float64
 3   3       690 non-null    object 
 4   4       690 non-null    object 
 5   5       690 non-null    object 
 6   6       690 non-null    object 
 7   7       690 non-null    float64
 8   8       690 non-null    object 
 9   9       690 non-null    object 
 10  10      690 non-null    int64  
 11  11      690 non-null    object 
 12  12      690 non-null    object 
 13  13      690 non-null    object 
 14  14      690 non-null    int64  
 15  15      690 non-null    object 
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB


#Handling Missing Values

In [ ]:
for i in dataset.columns:
    #print(i)
    if dataset[i].dtype==object:
        print(dataset[i].unique())

['b' 'a' '?']
['30.83' '58.67' '24.50' '27.83' '20.17' '32.08' '33.17' '22.92' '54.42'
 '42.50' '22.08' '29.92' '38.25' '48.08' '45.83' '36.67' '28.25' '23.25'
 '21.83' '19.17' '25.00' '47.75' '27.42' '41.17' '15.83' '47.00' '56.58'
 '57.42' '42.08' '29.25' '42.00' '49.50' '36.75' '22.58' '27.25' '23.00'
 '27.75' '54.58' '34.17' '28.92' '29.67' '39.58' '56.42' '54.33' '41.00'
 '31.92' '41.50' '23.92' '25.75' '26.00' '37.42' '34.92' '34.25' '23.33'
 '23.17' '44.33' '35.17' '43.25' '56.75' '31.67' '23.42' '20.42' '26.67'
 '36.00' '25.50' '19.42' '32.33' '34.83' '38.58' '44.25' '44.83' '20.67'
 '34.08' '21.67' '21.50' '49.58' '27.67' '39.83' '?' '37.17' '25.67'
 '34.00' '49.00' '62.50' '31.42' '52.33' '28.75' '28.58' '22.50' '28.50'
 '37.50' '35.25' '18.67' '54.83' '40.92' '19.75' '29.17' '24.58' '33.75'
 '25.42' '37.75' '52.50' '57.83' '20.75' '39.92' '24.75' '44.17' '23.50'
 '47.67' '22.75' '34.42' '28.42' '67.75' '47.42' '36.25' '32.67' '48.58'
 '33.58' '18.83' '26.92' '31.25' '56.50' 

In [ ]:
dataset = dataset.replace('?', np.nan)

In [ ]:
dataset.fillna(dataset.mean(), inplace = True)  #to fill missing value in numeric columns
dataset.isnull().sum()  #to find numbers of missing values in non-numeric columns because mean imputation will fail there

<ipython-input-72-241c2a38dd18>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataset.fillna(dataset.mean(), inplace = True)  #to fill missing value in numeric columns


0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

In [ ]:
for c in dataset:
  if dataset[c].dtype == object:
    dataset = dataset.fillna(dataset[c].value_counts().index[0]) #missing value in categorical columns, with most frequent values
dataset.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

#Non-Numeric Data to Numeric Data

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for c in dataset:
  if dataset[c].dtype == object:
    dataset[c] = le.fit_transform(dataset[c])

#Spliting Data into Train and Test data

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[1.000e+00 1.560e+02 0.000e+00 ... 0.000e+00 6.800e+01 0.000e+00]
 [0.000e+00 3.280e+02 4.460e+00 ... 0.000e+00 1.100e+01 5.600e+02]
 [0.000e+00 8.900e+01 5.000e-01 ... 0.000e+00 9.600e+01 8.240e+02]
 ...
 [0.000e+00 9.700e+01 1.350e+01 ... 0.000e+00 6.700e+01 1.000e+00]
 [1.000e+00 2.000e+01 2.050e-01 ... 0.000e+00 9.600e+01 7.500e+02]
 [1.000e+00 1.970e+02 3.375e+00 ... 0.000e+00 0.000e+00 0.000e+00]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#Rescalling the values to (0-1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_final = sc.fit_transform(X_train)
X_test_final = sc.fit_transform(X_test)

#Finding out best Classification model for this problem

Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X_train_final, y_train)

LogisticRegression()

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_log = logistic.predict(X_test_final)
print("Accuracy of logistic regression classifier: ", logistic.score(X_test_final, y_test)*100, "%")
print("Confusion Matrix of Logistic Regression: ")
print(confusion_matrix(y_test, y_pred_log))

Accuracy of logistic regression classifier:  85.5072463768116 %
Confusion Matrix of Logistic Regression: 
[[85 12]
 [18 92]]


Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dTree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dTree.fit(X_train_final, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_tree = dTree.predict(X_test_final)
print("Accuracy of Decision Tree classifier: ", dTree.score(X_test_final, y_test)*100, "%")
print("Confusion Matrix of Decision Tree: ")
print(confusion_matrix(y_test, y_pred_tree))

Accuracy of Decision Tree classifier:  83.09178743961353 %
Confusion Matrix of Decision Tree: 
[[76 21]
 [14 96]]


KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KnN = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KnN.fit(X_train_final, y_train)

KNeighborsClassifier()

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_knn = KnN.predict(X_test_final)
print("Accuracy of KNN classifier: ", KnN.score(X_test_final, y_test)*100, "%")
print("Confusion Matrix of KNN: ")
print(confusion_matrix(y_test, y_pred_knn))

Accuracy of KNN classifier:  87.43961352657004 %
Confusion Matrix of KNN: 
[[ 79  18]
 [  8 102]]


SVM

In [ ]:
from sklearn.svm import SVC
SvM = SVC(kernel = 'linear', random_state = 0)
SvM.fit(X_train_final, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_svm = SvM.predict(X_test_final)
print("Accuracy of support vector classifier using linear kernel: ", SvM.score(X_test_final, y_test)*100, "%")
print("Confusion Matrix of SVM using linear kernel: ")
print(confusion_matrix(y_test, y_pred_svm))

Accuracy of support vector classifier using linear kernel:  84.54106280193237 %
Confusion Matrix of SVM using linear kernel: 
[[90  7]
 [25 85]]


In [ ]:
from sklearn.svm import SVC
SvM2 = SVC(kernel = 'rbf', random_state = 0)
SvM2.fit(X_train_final, y_train)

SVC(random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_svm2 = SvM2.predict(X_test_final)
print("Accuracy of support vector classifier using rbf kernel: ", SvM2.score(X_test_final, y_test)*100, "%")
print("Confusion Matrix of SVM using rbf kernel: ")
print(confusion_matrix(y_test, y_pred_svm2))

Accuracy of support vector classifier using rbf kernel:  85.99033816425121 %
Confusion Matrix of SVM using rbf kernel: 
[[85 12]
 [17 93]]


Naive Bayes  Classification

In [ ]:
from sklearn.naive_bayes import GaussianNB
Naive = GaussianNB()
Naive.fit(X_train_final, y_train)

GaussianNB()

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_naive = Naive.predict(X_test_final)
print("Accuracy of Naive Bayes Classification : ", Naive.score(X_test_final, y_test)*100, "%")
print("Confusion Matrix of Naive Bayes Classification: ")
print(confusion_matrix(y_test, y_pred_naive))

Accuracy of Naive Bayes Classification :  76.32850241545893 %
Confusion Matrix of Naive Bayes Classification: 
[[ 57  40]
 [  9 101]]


Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
Forest = RandomForestClassifier(n_estimators = 13, criterion = 'entropy', random_state = 0)
Forest.fit(X_train_final, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=13, random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_forest = Forest.predict(X_test_final)
print("Accuracy of Random Forest Classification : ", Forest.score(X_test_final, y_test)*100, "%")
print("Confusion Matrix of Random Forest Classification: ")
print(confusion_matrix(y_test, y_pred_forest))

Accuracy of Random Forest Classification :  82.6086956521739 %
Confusion Matrix of Random Forest Classification: 
[[77 20]
 [16 94]]


After checking all, we find KNN is the best algorithm for this problem