<a href="https://colab.research.google.com/github/Shakya-Chakraborty/ML-Projects/blob/main/%20Breast%20Cancer%20Prediction/Breast_Cancer_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Importing Dataset

In [ ]:
dataset = pd.read_csv("Breast_cancer.csv")


In [ ]:
dataset.head()

id diagnosis  Radius_mean  Texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         21.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [ ]:
dataset.describe()

id  Radius_mean  Texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.296678       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301816       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.870000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count     569.000000  ...    569.000000     569.000000       569.000000   
mean        0.181162  ...     16.269190      25.677223       107.261213   
std         0.027414  ...      4.833242       6.146258        33.602542   
min         0.106000  ...      7.930000      12.020000        50.410000   
25%         0.161900  ...     13.010000      21.080000        84.110000   
50%         0.179200  ...     14.970000      25.410000        97.660000   
75%         0.195700  ...     18.790000      29.720000       125.400000   
max         0.304000  ...     36.040000      49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  
count            569.000000      569.000000               569.000000  
mean               0.114606        0.290076                 0.083946  
std                0.065732        0.061867                 0.018061  
min                0.000000        0.156500                 0.055040  
25%                0.064930        0.250400                 0.071460  
50%                0.099930        0.282200                 0.080040  
75%                0.161400        0.317900                 0.092080  
max                0.291000        0.663800                 0.207500  

[8 rows x 31 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   Radius_mean              569 non-null    float64
 3   Texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
X = dataset.iloc[:,2:].values
y = dataset.iloc[:,1].values

In [ ]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 2.177e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [ ]:
print(y)

['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M'
 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'M'
 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'M'
 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B

#Handling Missing Data

In [ ]:
dataset.isnull().sum()

id                         0
diagnosis                  0
Radius_mean                0
Texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

####No missing data

#Spliting Dataset in train and Test Data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, random_state= 42)

#Feature Scaling


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train2 = sc.fit_transform(X_train)
X_test2 = sc.fit_transform(X_test)

#Model Building

###Support Vector Classification


In [ ]:
from sklearn.svm import SVC
svc_classifier = SVC(kernel = 'linear', random_state = 0)
svc_classifier.fit(X_train2, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_svc = svc_classifier.predict(X_test2)
print("Accuracy of support vector classifier using linear kernel: ", svc_classifier.score(X_test2, y_test)*100, "%")
print("Confusion Matrix of SVM using linear kernel: ")
print(confusion_matrix(y_test, y_pred_svc))

Accuracy of support vector classifier using linear kernel:  97.6608187134503 %
Confusion Matrix of SVM using linear kernel: 
[[107   1]
 [  3  60]]


In [ ]:
from sklearn.svm import SVC
svc_classifier2 = SVC(kernel = 'rbf', random_state = 0)
svc_classifier2.fit(X_train2, y_train)

SVC(random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_svc2 = svc_classifier2.predict(X_test2)
print("Accuracy of support vector classifier using rbf kernel: ", svc_classifier2.score(X_test2, y_test)*100, "%")
print("Confusion Matrix of SVM using rbf kernel: ")
print(confusion_matrix(y_test, y_pred_svc2))

Accuracy of support vector classifier using rbf kernel:  98.24561403508771 %
Confusion Matrix of SVM using rbf kernel: 
[[107   1]
 [  2  61]]


###Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X_train2, y_train)

LogisticRegression()

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_log = logistic.predict(X_test2)
print("Accuracy of logistic regression classifier: ", logistic.score(X_test2, y_test)*100, "%")
print("Confusion Matrix of Logistic Regression: ")
print(confusion_matrix(y_test, y_pred_log))

Accuracy of logistic regression classifier:  97.6608187134503 %
Confusion Matrix of Logistic Regression: 
[[107   1]
 [  3  60]]


###KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KnN = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KnN.fit(X_train2, y_train)

KNeighborsClassifier()

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_knn = KnN.predict(X_test2)
print("Accuracy of KNN classifier: ", KnN.score(X_test2, y_test)*100, "%")
print("Confusion Matrix of KNN: ")
print(confusion_matrix(y_test, y_pred_knn))

Accuracy of KNN classifier:  97.07602339181285 %
Confusion Matrix of KNN: 
[[107   1]
 [  4  59]]


###Decission Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dTree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dTree.fit(X_train2, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_tree = dTree.predict(X_test2)
print("Accuracy of Decision Tree classifier: ", dTree.score(X_test2, y_test)*100, "%")
print("Confusion Matrix of Decision Tree: ")
print(confusion_matrix(y_test, y_pred_tree))

Accuracy of Decision Tree classifier:  96.49122807017544 %
Confusion Matrix of Decision Tree: 
[[107   1]
 [  5  58]]


###Naive Bayes Classification

In [ ]:
from sklearn.naive_bayes import GaussianNB
Naive = GaussianNB()
Naive.fit(X_train2, y_train)

GaussianNB()

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_naive = Naive.predict(X_test2)
print("Accuracy of Naive Bayes Classification : ", Naive.score(X_test2, y_test)*100, "%")
print("Confusion Matrix of Naive Bayes Classification: ")
print(confusion_matrix(y_test, y_pred_naive))

Accuracy of Naive Bayes Classification :  94.73684210526315 %
Confusion Matrix of Naive Bayes Classification: 
[[105   3]
 [  6  57]]


###Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
Forest = RandomForestClassifier(n_estimators = 13, criterion = 'entropy', random_state = 0)
Forest.fit(X_train2, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=13, random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred_forest = Forest.predict(X_test2)
print("Accuracy of Random Forest Classification : ", Forest.score(X_test2, y_test)*100, "%")
print("Confusion Matrix of Random Forest Classification: ")
print(confusion_matrix(y_test, y_pred_forest))

Accuracy of Random Forest Classification :  97.07602339181285 %
Confusion Matrix of Random Forest Classification: 
[[107   1]
 [  4  59]]


####Note: We can see SVM with rbf kernel is the best classification model for this problem

In [ ]:
columns = []
for col in dataset.columns:
  columns.append(col)
columns.remove("id")
columns.remove("diagnosis")
print(columns)

['Radius_mean', 'Texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_worst', 'concavity_worst', 'concave points_worst', 'symmetry_worst', 'fractal_dimension_worst']


In [ ]:
print(X[469])

[1.162e+01 1.818e+01 7.638e+01 4.088e+02 1.175e-01 1.483e-01 1.020e-01
 5.564e-02 1.957e-01 7.255e-02 4.101e-01 1.740e+00 3.027e+00 2.785e+01
 1.459e-02 3.206e-02 4.961e-02 1.841e-02 1.807e-02 5.217e-03 1.336e+01
 2.540e+01 8.814e+01 5.281e+02 1.780e-01 2.878e-01 3.186e-01 1.416e-01
 2.660e-01 9.270e-02]


#Predict Output

In [ ]:
values = [0] * len(columns)
for i in range(0,len(columns)):
  print(f"Enter values for {columns[i]}")
  values[i] = float(input())


In [ ]:
len(values)

30

In [ ]:
values

[11.62,
 18.18,
 76.38,
 408.8,
 0.1175,
 0.1483,
 0.102,
 0.05564,
 0.1957,
 0.07255,
 0.4101,
 1.74,
 3.027,
 27.85,
 0.01459,
 0.03206,
 0.04961,
 0.01841,
 0.01807,
 0.005217,
 13.36,
 25.4,
 88.14,
 528.1,
 0.178,
 0.2878,
 0.3186,
 0.1416,
 0.266,
 0.0927]

In [ ]:
np.reshape((values),(1, 30))

array([[1.162e+01, 1.818e+01, 7.638e+01, 4.088e+02, 1.175e-01, 1.483e-01,
        1.020e-01, 5.564e-02, 1.957e-01, 7.255e-02, 4.101e-01, 1.740e+00,
        3.027e+00, 2.785e+01, 1.459e-02, 3.206e-02, 4.961e-02, 1.841e-02,
        1.807e-02, 5.217e-03, 1.336e+01, 2.540e+01, 8.814e+01, 5.281e+02,
        1.780e-01, 2.878e-01, 3.186e-01, 1.416e-01, 2.660e-01, 9.270e-02]])

In [ ]:
pred = svc_classifier2.predict(np.reshape((values),(1, 30)))

In [ ]:
pred

array(['M'], dtype=object)